apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: spring-webdb
  name: spring-webdb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: spring-webdb
  template:
    metadata:
      labels:
        app.kubernetes.io/name: spring-webdb
        app.kubernetes.io/part-of: spring-webdb
        tanzu.app.live.view: "true"
        tanzu.app.live.view.application.name: spring-webdb
    spec:
      containers:
      - image: spring-webdb:1.0.0
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 15
        name: app
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 15