apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: spring-webdb
  name: spring-webdb
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app.kubernetes.io/name: spring-webdb
  sessionAffinity: None
  type: LoadBalancer